# Loads default set of integrations. Do not remove.
default_config:

logger:
  default: info
  logs:
    custom_components.adaptive_hvac: debug

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# --- Dummy Entities for Testing ---

# 1. Fake Heater Switch
input_boolean:
  fake_heater:
    name: Fake Heater
    icon: mdi:radiator
  fake_window:
    name: Fake Window
    icon: mdi:window-closed-variant
    initial: true
  fake_heater_two:
    name: Fake Heater Two
    icon: mdi:radiator

# 2. Fake Temperature Slider (Simulate Room Temp)
input_number:
  fake_temperature:
    name: Fake Room Temp
    min: 10
    max: 30
    step: 0.5
    unit_of_measurement: "째C"
    icon: mdi:thermometer
  fake_temperature_two:
    name: Fake Room Temp
    min: 10
    max: 30
    step: 0.5
    unit_of_measurement: "째C"
    icon: mdi:thermometer


# 3. Template Sensor (Generic Thermostat needs a sensor, not an input_number)
template:
  - sensor:
      - name: "Fake Room Temperature"
        unit_of_measurement: "째C"
        state: "{{ states('input_number.fake_temperature') }}"
        device_class: temperature
  - sensor:
      - name: "Fake Room Temperature Two"
        unit_of_measurement: "째C"
        state: "{{ states('input_number.fake_temperature_two') }}"
        device_class: temperature

# 4. Generic Thermostat
climate:
  - platform: generic_thermostat
    name: Study
    heater: input_boolean.fake_heater
    target_sensor: sensor.fake_room_temperature
    min_temp: 15
    max_temp: 25
    ac_mode: false
    target_temp: 21
    cold_tolerance: 0.3
    hot_tolerance: 0.3
  - platform: generic_thermostat
    name: Bedroom
    heater: input_boolean.fake_heater_two
    target_sensor: sensor.fake_room_temperature_two
    min_temp: 15
    max_temp: 25
    ac_mode: false
    target_temp: 21
    cold_tolerance: 0.3
    hot_tolerance: 0.3

